startDelaySeconds: 0
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["org.hippoecm.repository:type=Repository,name=statistics", "org.onehippo.hst:type=Caching,*", "org.onehippo.hst:type=SessionPool,*", "java.lang:type=Memory,*", "java.lang:type=Threading,*", "Catalina:*"]
# Full config.yaml example at https://github.com/prometheus/jmx_exporter