version: '3.4'
services:
  brxm:
    image: org.example/myproject:0.1.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      METRICS_PORT: 8081
      profile: h2
      REPO_BOOTSTRAP: "true"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
